# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e2a807246e7c5026c233c360786fb457275a76e4012c1e49604b68d45e629c74a90596afcfe5dab49ae912d5aef808a23e67a4ba750051fe7681fa05c697981

test:
  secret_key_base: 2f385875d389078ad85dc264bad428e0258d0c59959dbd72eee2a86b4ae7d82119c2fbeeab582e87005aaf535bab6ed3a44e159df79ee043b588aeda9a55b4ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
